apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: '2020-06-11T22:56:44Z'
  creationTimestamp: '2020-06-04T03:52:01Z'
  generation: 6
  labels:
    app.kubernetes.io/instance: customer-info-api
  name: customer-info-api
  namespace: development
  resourceVersion: '18745592'
  selfLink: >-
    /apis/image.openshift.io/v1/namespaces/development/imagestreams/customer-info-api
  uid: 22f4c20b-391a-4a97-93a8-f680fbc82867
spec:
  dockerImageRepository: quay.io/neinnovationorg/customer-info-api
  lookupPolicy:
    local: false
  tags:
      - from:
        kind: DockerImage
        name: 'quay.io/neinnovationorg/customer-info-api:dev'
      generation: 6
      importPolicy: {}
      name: dev
      referencePolicy:
        type: Source
status:
  dockerImageRepository: >-
    image-registry.openshift-image-registry.svc:5000/development/customer-info-api
  tags:
    - items:
        - created: '2020-06-11T22:56:44Z'
          dockerImageReference: >-
            quay.io/neinnovationorg/customer-info-api@sha256:0ac1aa3858dfe14d57274cdc75ca782bfc76a54a24170498bf5eed9a466a4abb
          generation: 6
          image: >-
            sha256:0ac1aa3858dfe14d57274cdc75ca782bfc76a54a24170498bf5eed9a466a4abb
      tag: dev
