apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck
  labels:
    app.kubernetes.io/instance: customer-info-api
  name: customer-info-api
  namespace: development
spec:
  dockerImageRepository: quay.io/neinnovationorg/customer-info-api
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/neinnovationorg/customer-info-api:dev'
      importPolicy: {}
      name: dev
      referencePolicy:
        type: Source
status:
  dockerImageRepository:image-registry.openshift-image-registry.svc:5000/development/customer-info-api
  tags:
    - items:
          dockerImageReference: quay.io/neinnovationorg/customer-info-api@sha256:0ac1aa3858dfe14d57274cdc75ca782bfc76a54a24170498bf5eed9a466a4abb
          image: sha256:0ac1aa3858dfe14d57274cdc75ca782bfc76a54a24170498bf5eed9a466a4abb
      tag: dev
