# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "##[set-output name=sha_short;]$(echo $(git rev-parse --short HEAD))"
      id: extract_branch
    - name: Set Constants
      id: consts
      run: |
        echo ::set-output name=repo::$(echo ${GITHUB_REPOSITORY})
        echo ::set-output name=sha_short::$(git rev-parse --short HEAD)
        echo ::set-output name=image-name::$(echo quay.io/neinnovationorg/customer-info-api})
        echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
        echo ::set-output name=docker_repo::$(echo /neinnovationorg/customer-info-api)
        
        
#    - run: npm ci
#    - run: npm run build --if-present
#    - run: npm test
    - name: Creating Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                 # If blank, default: triggered branch
        destination_branch: "dev"      # If blank, default: master
        pr_title: "Update new image tag from ${{ github.ref }} into dev" # Title of pull request:
        github_token: ${{ secrets.GITHUB_TOKEN }}
